language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - 0.5
    - 0.6
    - nightly
notifications:
    email: false

matrix:
  allow_failures:
    - julia: nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("DetectionTheory"); Pkg.test("DetectionTheory"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("DetectionTheory")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
